ascii_composer:
  good_old_caps_lock: true
  switch_key:
    Caps_Lock: noop
    Control_L: noop
    Control_R: noop
    Eisu_toggle: clear
    Shift_L: commit_code
    Shift_R: commit_code
config_version: 0.36.custom.2889675771
customization: 2889675771
key_binder:
  bindings:
    - {accept: "Shift+space", toggle: full_shape, when: always}
    - {accept: bracketleft, send: Page_Up, when: has_menu}
    - {accept: bracketright, send: Page_Down, when: has_menu}
menu:
  page_size: 5
punctuator:
  half_shape:
    "!": "！"
    "\"": {pair: ["“", "”"]}
    "$": "￥"
    "'": {pair: ["‘", "’"]}
    ",": "，"
    .: "。"
    "/": "/"
    ":": "："
    ";": "；"
    "<": "《"
    ">": "》"
    "?": "？"
    "[": "【"
    "\\": "、"
    "]": "】"
    "^": "……"
    _: "——"
    "|": "·"
recognizer:
  patterns:
    email: "^[A-Za-z][-_.0-9A-Za-z]*@.*$"
    uppercase: "[A-Z][-_+.'0-9A-Za-z]*$"
    url: "^(www[.]|https?:|ftp[.:]|mailto:|file:).*$|^[a-z]+[.].+$"
schema_list:
  - schema: pinyin_simp
switcher:
  caption: "〔方案选单〕"
  hotkeys:
    - "Control+grave"